text_file = open("4.txt", "wt")
text_file.write("Плескач Матвій Русланович, 10 балів\n")
text_file.write("Авдєєва Серафима, 17,5 балів\n")
text_file.write("Блінда Ірина, 15 балів\n")
text_file.write("Векслер Поліна, 17,5  балів\n")
text_file.write("Римарович Павло, 17,5 балів\n")
text_file.write("Трутень Дмитро, 17,5 балів\n")
text_file.write("Пироженко Іван, 17 балів\n")
text_file.write("Яременко Вікторія, 15 балів\n")
text_file.write("Удод Ілля, 7 балів\n")
text_file.close()

text_file = open("5.txt", "wt")
text_file.write("Волостнов Павло Ярославович, 0 балів\n")
text_file.write("Гринюк Андрій Валерійович, 0 балів\n")
text_file.write("Домбровський Владислав Васильович, 0 балів\n")
text_file.write("Кужель Дмитро Bікторович, 0 балів\n")
text_file.write("Лиска Вадим Максимович, 0 балів\n")
text_file.write("Mішакін Iлля Iгорович, 0 балів\n")
text_file.write("Мошківський Михайло Михайлович, 0 балів\n")
text_file.write("Нагорнюк Олександра Iваніiвна, 0 балів")
text_file.close()

text_file = open("6.txt", "wt")
text_file.write("Астафьєва Bікторія Сергіївна, 12,5 балів \n")
text_file.write("Максим Максимович, 6,5 балів \n")
text_file.write("Сорокін Олександр Biталійович, 12,5 \n")
text_file.write("Вiталій Олександрович, 10 балів \n")
text_file.write("Дубовий Вадим Русланович, 0 балів \n")
text_file.write("Никифоров Харитон, 9 балов\n")
text_file.write("Чан Вьет Ань, 4 балів\n")
text_file.close()
